using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace VueCoreFramework.Models.AccountViewModels
{
    /// <summary>
    /// A ViewModel used to transfer information during a user account password reset.
    /// </summary>
    public class ResetPasswordViewModel
    {
        /// <summary>
        /// The email address of the user account.
        /// </summary>
        [Required]
        [EmailAddress]
        public string Email { get; set; }

        /// <summary>
        /// The new password for the user account.
        /// </summary>
        [Required]
        [StringLength(24, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        public string NewPassword { get; set; }

        /// <summary>
        /// The new password for the user account, repeated.
        /// </summary>
        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }

        /// <summary>
        /// The code generated to identify the callback link in the email generated by the operation.
        /// </summary>
        public string Code { get; set; }

        /// <summary>
        /// A list of errors generated during the operation.
        /// </summary>
        public List<string> Errors { get; set; }
    }
}
