<template>
    <div class="wrapper">
        <v-text-field :type="schema.inputType"
                      :value="value"
                      @input="value = $event"
                      @change="onChange"
                      :accept="schema.accept"
                      :alt="schema.alt"
                      :append-icon="schema.inputType === 'password' ? (pwVis ? 'visibility' : 'visibility_off') : ''"
                      :append-icon-cb="() => (pwVis = !pwVis)"
                      :autocomplete="schema.autocomplete"
                      :checked="schema.checked"
                      :counter="value.length > schema.max"
                      :dirname="schema.dirname"
                      :disabled="disabled || schema.readonly"
                      :errors="errors"
                      :files="schema.files"
                      :formaction="schema.formaction"
                      :formenctype="schema.formenctype"
                      :formmethod="schema.formmethod"
                      :formnovalidate="schema.formnovalidate"
                      :formtarget="schema.formtarget"
                      :height="schema.height"
                      :hint="schema.hint"
                      :label="schema.placeholder"
                      :list="schema.list"
                      :max="schema.max"
                      :maxlength="schema.maxlength"
                      :min="schema.min"
                      :multi-line="schema.inputType === 'textArea'"
                      :multiple="schema.multiple"
                      :name="schema.inputName"
                      :prepend-icon="schema.icon"
                      :persistent-hint="schema.hint"
                      :prefix="schema.prefix"
                      :required="schema.required"
                      :rows="schema.rows"
                      :rules="[rules]"
                      :size="schema.size"
                      :src="schema.src"
                      :step="schema.step"
                      :width="schema.width"
                      :suffix="schema.suffix"></v-text-field>
        <span class="helper" v-if="schema.inputType === 'color' || schema.inputType === 'range'">{{ value }}</span>
    </div>
</template>

<script src="./fieldVuetifyText.ts"></script>